services:
  mysql:
    image: mysql:8
    container_name: ${APP_NAME}_mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    container_name: ${APP_NAME}_php
    volumes:
      - ./:/var/www
    working_dir: /var/www

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}_nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    ports:
      - ${NGINX_PORT}:80

volumes:
  dbdata:
